name: flutter_firebase_chat_core
description: >
  Actively maintained, community-driven Firebase BaaS for chat applications
  with an optional chat UI.
version: 1.5.0
homepage: https://flyer.chat
repository: https://github.com/flyerhq/flutter_firebase_chat_core
publish_to: "none"
environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: ^3.1.17
  firebase_auth: ^3.3.19
  flutter_chat_types: ^3.2.0
  meta: ^1.3.0
  flipper_models: ^0.0.1-dev.7
